name: Charlie
favicon: null
layout_spectrum: 0.36503752414137125
typography_spectrum: 0.9127250974997878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9914236136246473
  lightness: 0.10842936811968684
  saturation: 0.11079567461274564
  rhythmicContrast: 0.29142780415713787
purpose: []
