name: Charlie
favicon: null
layout_spectrum: 0.60366
typography_spectrum: 0.9127250974997878
title: Charlie Triplett - Columbia Missouri Web Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#39b54a'
    - '#325460'
    - '#ffffff'
    - '#a8dfb0'
    - '#008000'
  brandStrength: 1
  lightness: 0.10842936811968684
  saturation: 0.11079567461274564
  rhythmicContrast: 0.29142780415713787
purpose: []
